import { Navbar } from "@/components/Navbar"

import "../globals.css";
import { NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger } from "@/components/ui/navigation-menu"
import { NavbarDashboard } from "../ui/Screens/DashboarScreen/NavbarDashboard/NavbarDashboard";
import { Footer } from "@/components/Footer";
import { AsideDashBoard } from "../ui/components/AsideDashboard";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default  function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const classAside=[]
  

  return (
    <html lang="en">
      <body >
      <main>
          <div>
            <NavbarDashboard/>
          <div >

          <AsideDashBoard/>
            <section className="relative md:left-[15%] md:w-[85%]" >
            {children}
            <div className="mt-40">

              <Footer/>
            </div>
            </section>
      </div>
    </div>
      </main>
        </body>
    </html>
  )
}
